export default [
  // {
  //   slug: "early-human-timeline",
  //   title: "Early Human Timeline",
  //   image: "articles/early-human.jpg",
  //   imageAlt: "A prehistoric human holding a spear, gazing up at a star-filled night sky.",
  //   blurb: "stub",
  //   tags: ["history", "timeline"],
  // },
  // {
  //   slug: "earth-timeline",
  //   title: "Earth Timeline",
  //   image: "articles/earth.jpg",
  //   imageAlt: "Earth from space, showing continents, oceans, and cloud formations against a star-filled background.",
  //   blurb: "stub",
  //   tags: ["nature", "geology", "evolution", "timeline"],
  // },
  {
    slug: "universe-timeline",
    title: "Universe Timeline",
    image: "articles/universe.jpg",
    imageAlt: "A nebula with gas clouds and bright stars against a dark sky.",
    blurb: "Timeline of the most important events and eras from the Big Bang to Earth's formation.",
    tags: ["astrophysics", "timeline"],
  },
  {
    slug: "stellar-evolution",
    title: "Stellar Evolution",
    image: "articles/stellar-evolution.jpg",
    imageAlt: "A bright star with a glowing ring and radiating light beams, surrounded by a spherical cloud of scattered stars.",
    blurb: "Overview of how stars form, what elements they create, and how they end their existence.",
    tags: ["astrophysics", "chemistry"],
  },
  {
    slug: "sugar-and-children",
    title: "Sugar and Children",
    image: "articles/sugar-girl.jpg",
    imageAlt: "A young woman in Gothic Lolita fashion sipping tea and holding a fork over a slice of strawberry shortcake at a vintage café table, surrounded by flowers, fine china, and a pastry display case.",
    blurb: "Non-alarmist science-based take on sugar in child diet. Because while the difference between “natural” and “added” sugar is a well-meaning and sometimes even useful heuristic, it shouldn't be treated as anything more than that.",
    tags: ["nutrition", "parenting"],
  },
  {
    slug: "crop-rotation",
    title: "Crop Rotation",
    image: "articles/farmland.jpg",
    imageAlt: "A winding dirt path alongside a weathered wooden fence through golden wheat fields, leading toward a distant farmhouse and the sea under a cloudy sky.",
    blurb: "Overview of what crop rotation is, why it was used, and what the benefits are.",
    tags: ["agriculture", "history"],
  },
  {
    slug: "screens-and-children",
    title: "Screens and Children",
    image: "articles/screen-witch.jpg",
    imageAlt: "A cozy anime-style illustration of a young witch in a black star-patterned robe and a witch hat adorned with wildflowers, seated in a red velvet armchair and scrolling on her phone by candlelight.",
    blurb: "Non-alarmist science-based take on children using screens. Because while the “screens are bad” is a well-meaning and sometimes even useful heuristic, it shouldn't be treated as anything more than that.",
    tags: ["technology", "parenting"],
  },
  {
    slug: "foxes",
    title: "Foxes",
    image: "articles/fox.jpg",
    imageAlt: "A red fox resting on a large rock with eyes closed and head tilted upward, appearing content and relaxed, with a blurred snowy background.",
    blurb: "Test article – basic information about foxes that every human should know.",
    tags: ["nature"],
  },
];
